### ISSUE TITLE
crypto dependency breaks react native

### ISSUE THREAD

**Issue by madc** [feathersjs/feathers-offline-realtime#9]
With feathers-offline-realtime version 0.1.1 the [crypto node module](https://nodejs.org/api/crypto.html) was added as a dependency, what breaks react native compatibility. The result is more or less [this error](https://stackoverflow.com/questions/29836434/requiring-unknown-module-crypto-in-react-native-environment).

Version 0.1.0 works fine with React Native.

**Comment by eddyystop** [comment]
`npm i --save crypto` should solve the issue for the moment. Thanks for the catch.

**Comment by madc** [comment]
I'll have to check tomorrow, but I have a feeling, this could be a bit more complicated. See [Please remove this module from npm](https://github.com/Gozala/crypto/issues/14)

**Comment by eddyystop** [comment]
The issue you linked to only complains about the npm name being used.

Could you please see if feathers-offline-realtime works after `npm i --save crypto`?

If not, you can remove the `hash` and `hashOfRecords` functions from src/commons/utils/crypotographic.js . This allows the import to be dropped.

A good and cross-platform hash function is needed to implement optimistic mutation while disconnected.

**Comment by madc** [comment]
What I was trying to point out with that link is, that this module is not a replacement/polyfill for the native node module. Installing `crypto` does not solve this issue.
As far as i can see, the hash functions are not used yet, would it be possible to move it to a develop branch and release a new version including the changes regarding uuid and optimistic mutation?

**Comment by eddyystop** [comment]
I am not looking for a pollyfill for the native Node module. I just want a SHA1 hash.

I am still unclear from your answer if you did try the npm cypto module or not.

This repo will need a cross-platform SHA1 hash within days, so I'd be grateful if you tried `npm i --save crypto`  as I can't work with React Native the next few days.

**Comment by madc** [comment]
Ok, sorry. I did try and it did not work.

**Comment by madc** [comment]
Could [brix/crypto-js](https://github.com/brix/crypto-js) be a solution? Haven't used it yet, [but it seems to work](https://stackoverflow.com/questions/33312281/react-native-crypto-how-to-generate-hmac-in-react-native) with react native too.

**Comment by eddyystop** [comment]
i should have been explicit that `npm i --save crypto` should be run inside the feathers-offline-realtime folder. i hope that's what you tried.

i won't be able to type with more than 1 finger for 5 days or more.

perhaps you can try in the right folder if you didn't for knowledge sake. i'll look at your suggestion. thanks.

**Comment by eddyystop** [comment]
i may be wrong, but as far as i can see brix/crypto-js creates and depends on global variables. i hope there's something that follows node standards better and has a good number of github stars.

the [error](https://stackoverflow.com/questions/29836434/requiring-unknown-module-crypto-in-react-native-environment) issue you mention getting mentions using `rn-nodeify`, i keep running across comments saying to try that while looking into this issue. have you tried that?

**Comment by eddyystop** [comment]
this [repo](https://www.npmjs.com/package/md5) states it works on node & browser. a feathere core member has used in in react native.

**Comment by eddyystop** [comment]
I expect this is fixed with https://github.com/feathersjs/feathers-offline-realtime/pull/11 . It'll be published as 0.1.2.

**Comment by madc** [comment]
Perfect, works like a charm!
